df:
  open:
    swagger:
     #path: '/server/*'
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadataMap:
      version: 2.0.0
      app: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka
    healthcheck:
      enabled: false

