server:
  port: 7110
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://localhost:7100/eureka
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85
    evictionIntervalTimerInMs: 3000
    delta-retention-timer-interval-in-ms: 3000

